// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehzvmqsmyhdabuxnnsqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoenZtcXNteWhkYWJ1eG5uc3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTU4OTAsImV4cCI6MjA3Mzg5MTg5MH0.d2qZWAwBkrGO-Cqs2k2Yx76Mx5i5GzuNaKN9vzsyUEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});